### ISSUE TITLE
Steve on Players

### ISSUE THREAD

**Issue by KipperedSnack** [minotar/minotar.net#13]
All of a sudden 90% of the usernames I run through or have on my site are showing "Steve" skin. Even tho all of them have skins. 

Please advise. Using nodebb-plugin-minotar. Latest.

**Comment by LukeHandle** [comment]
Hey there @KipperedSnack, thanks for reaching out and apologies for the inconvenience caused here. We are aware of the issue here and tracking over in https://github.com/minotar/imgd/issues/181

The crux of the issue is that Mojang changed (or seemingly deprecated) an API they used to provide. The new API we need to use to allow Username lookups does not allow the volume of requests needed by Minotar (a victim of our popularity).

I tried deploying the new code 17 hours after the issue was first seen, but almost immediately, we hit the limits.

Currently, the skin lookups is falling back to the (very) old S3 storage for Skins - thus for users who have not changed their skin, they will have a very old render.

Again, please accept my apologies, this is very painful for me as well. There are some potential solutions we are working through and will update that other issue when we have more info.

===

One last question @KipperedSnack, does that plugin allow lookup based on UUID?

**Comment by KipperedSnack** [comment]
Thank you. And sorry for your troubles with Mojang. 

The nodebb-plugin-minotar does NOT use UUID as far as I can see nor is it capable:

https://github.com/ArkenaMC/nodebb-plugin-minotar/blob/master/library.js

Appears to just use the forum username as the lookup. Hope this helps.

**Comment by LukeHandle** [comment]
It's logged over here https://bugs.mojang.com/browse/MC-125157 (though the comments just disappeared). Other's are having issues with the API and it was confirmed by Dinnerbone as deprecated. I'm hopeful they will make things a bit easier here, but we'll see.

**Comment by KipperedSnack** [comment]
This was a stupid decision on Dinnerbones' part. 

I hate that they are continual pushing everyone to newer MC versions.  I can't even adjust my code to lookup the UUID from the Mojang profile, as it I hit the limit first page load of all users. 

Ridiculous. Only thing I can think of is locally caching uuid whilst the account is created etc. Then perform the lookups via Crafatar or something. 

Let me know if you figure anything out... please.

**Comment by KipperedSnack** [comment]
Kinda just came back...

**Comment by LukeHandle** [comment]
Hey @KipperedSnack, We spun up _a lot_ more servers here and this is "resolved" in the short term. We're now operating at 13 times our previous capacity in terms of backend. When I have time in the coming weeks I will work on optimizing things here. We'll use the metrics from this period to then adjust the capacity as required.
