### ISSUE TITLE
Steve

### ISSUE THREAD

**Issue by opiepl** [minotar/minotar.net#20]
Is the api down? When trying to get player's head it shows steve.

**Comment by clone1018** [comment]
Can you provide the username you are trying? Mojang heavily throttles their API unfortunately, but I can try it out.

**Comment by opiepl** [comment]
For example Samarekk

**Comment by opiepl** [comment]
> For example Samarekk

https://minotar.net/avatar/Adexion didn't work too

**Comment by clone1018** [comment]
According to https://mcuuid.net/?q=Samarekk that username is not a valid username.

**Comment by opiepl** [comment]
> According to https://mcuuid.net/?q=Samarekk that username is not a valid username.

my bad, TheSamarek, but still don't work and some other usernames such as "Trolgamer554" and other don't work :(

**Comment by clone1018** [comment]
I can reproduce the problem, thank you! Will look into it soon.

**Comment by LukeHandle** [comment]
It appears we had been hitting ratelimits on the sessionserver API. After reviewing some of our usage, it appears since we wrote that logic (years ago), the ratelimiting has changed to be more aggressive. I believe though that this particular issue should now be resolved, though I will keep an eye on it over the next day. Skins should load again over the next few hours as the error cache clears out.

**Comment by LukeHandle** [comment]
I can see this change is working well and we're back to normal rates:

![2021_06_29_1341_chrome_hHe](https://user-images.githubusercontent.com/799079/123799067-bc191880-d8df-11eb-9216-f8fb76deae46.png)
